export const INDIA_STATES = [
  'Andaman and Nicobar Islands',
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chandigarh',
  'Chhattisgarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jammu and Kashmir',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Ladakh',
  'Lakshadweep',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Puducherry',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
] as const;

export type IndiaState = (typeof INDIA_STATES)[number];

export const INDIA_CITIES: Record<IndiaState, string[]> = {
  'Andaman and Nicobar Islands': ['Port Blair', 'Diglipur', 'Rangat', 'Mayabunder'],
  'Andhra Pradesh': [
    'Visakhapatnam', 'Vijayawada', 'Guntur', 'Nellore', 'Kurnool', 'Rajahmundry',
    'Kakinada', 'Tirupati', 'Anantapur', 'Kadapa', 'Eluru', 'Ongole', 'Vizianagaram',
    'Srikakulam', 'Nandyal', 'Proddatur', 'Chittoor', 'Tenali',
  ],
  'Arunachal Pradesh': ['Itanagar', 'Naharlagun', 'Tawang', 'Ziro', 'Pasighat', 'Bomdila'],
  'Assam': [
    'Guwahati', 'Silchar', 'Dibrugarh', 'Jorhat', 'Nagaon', 'Tinsukia', 'Tezpur',
    'Bongaigaon', 'Dhubri', 'Diphu', 'North Lakhimpur', 'Sivasagar',
  ],
  'Bihar': [
    'Patna', 'Gaya', 'Bhagalpur', 'Muzaffarpur', 'Purnia', 'Darbhanga', 'Bihar Sharif',
    'Arrah', 'Begusarai', 'Katihar', 'Munger', 'Chhapra', 'Danapur', 'Bettiah',
    'Saharsa', 'Sasaram', 'Hajipur', 'Dehri',
  ],
  'Chandigarh': ['Chandigarh', 'Manimajra', 'Panchkula'],
  'Chhattisgarh': [
    'Raipur', 'Bhilai', 'Bilaspur', 'Korba', 'Durg', 'Rajnandgaon', 'Raigarh',
    'Jagdalpur', 'Ambikapur', 'Dhamtari', 'Mahasamund',
  ],
  'Dadra and Nagar Haveli and Daman and Diu': ['Daman', 'Diu', 'Silvassa'],
  'Delhi': [
    'New Delhi', 'Delhi', 'Dwarka', 'Rohini', 'Janakpuri', 'Saket', 'Lajpat Nagar',
    'Shahdara', 'Pitampura', 'Karol Bagh', 'Connaught Place', 'Noida (Delhi NCR)',
    'Gurugram (Delhi NCR)',
  ],
  'Goa': ['Panaji', 'Vasco da Gama', 'Margao', 'Mapusa', 'Ponda', 'Bicholim', 'Sanquelim'],
  'Gujarat': [
    'Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Gandhinagar', 'Bhavnagar', 'Jamnagar',
    'Junagadh', 'Anand', 'Navsari', 'Bharuch', 'Morbi', 'Nadiad', 'Mehsana',
    'Surendranagar', 'Valsad', 'Porbandar', 'Gondal',
  ],
  'Haryana': [
    'Gurugram', 'Faridabad', 'Panipat', 'Ambala', 'Yamunanagar', 'Rohtak', 'Hisar',
    'Karnal', 'Sonipat', 'Panchkula', 'Bhiwani', 'Sirsa', 'Bahadurgarh', 'Jind',
    'Thanesar', 'Kaithal', 'Rewari', 'Palwal',
  ],
  'Himachal Pradesh': [
    'Shimla', 'Solan', 'Dharamshala', 'Mandi', 'Palampur', 'Baddi', 'Nahan',
    'Kullu', 'Manali', 'Hamirpur', 'Una', 'Chamba', 'Bilaspur',
  ],
  'Jammu and Kashmir': [
    'Srinagar', 'Jammu', 'Anantnag', 'Sopore', 'Kathua', 'Baramulla', 'Udhampur',
    'Rajouri', 'Punch', 'Kupwara',
  ],
  'Jharkhand': [
    'Ranchi', 'Jamshedpur', 'Dhanbad', 'Bokaro', 'Deoghar', 'Phusro', 'Hazaribagh',
    'Giridih', 'Ramgarh', 'Medininagar', 'Chirkunda', 'Dumka',
  ],
  'Karnataka': [
    'Bengaluru', 'Mysuru', 'Hubli', 'Mangaluru', 'Belagavi', 'Kalaburagi', 'Ballari',
    'Vijayapura', 'Shivamogga', 'Tumkur', 'Davangere', 'Bidar', 'Udupi', 'Hassan',
    'Dharwad', 'Chitradurga', 'Raichur', 'Hassan', 'Gadag', 'Bagalkot',
  ],
  'Kerala': [
    'Thiruvananthapuram', 'Kochi', 'Kozhikode', 'Thrissur', 'Kannur', 'Kollam',
    'Palakkad', 'Alappuzha', 'Malappuram', 'Manjeri', 'Thodupuzha', 'Kottayam',
    'Kasaragod', 'Pathanamthitta', 'Idukki', 'Wadakkanchery',
  ],
  'Ladakh': ['Leh', 'Kargil'],
  'Lakshadweep': ['Kavaratti', 'Agatti'],
  'Madhya Pradesh': [
    'Bhopal', 'Indore', 'Jabalpur', 'Gwalior', 'Ujjain', 'Sagar', 'Dewas', 'Satna',
    'Ratlam', 'Rewa', 'Murwara', 'Singrauli', 'Burhanpur', 'Khandwa', 'Bhind',
    'Chhindwara', 'Shivpuri', 'Vidisha', 'Damoh', 'Mandsaur',
  ],
  'Maharashtra': [
    'Mumbai', 'Pune', 'Nagpur', 'Thane', 'Nashik', 'Aurangabad', 'Solapur', 'Kalyan',
    'Mira-Bhayandar', 'Navi Mumbai', 'Vasai-Virar', 'Sangli', 'Malegaon', 'Jalgaon',
    'Akola', 'Latur', 'Dhule', 'Ahmednagar', 'Ichalkaranji', 'Chandrapur',
    'Parbhani', 'Bhiwandi', 'Amravati', 'Nanded', 'Kolhapur',
  ],
  'Manipur': ['Imphal', 'Thoubal', 'Kakching', 'Bishnupur', 'Senapati', 'Churachandpur'],
  'Meghalaya': ['Shillong', 'Tura', 'Jowai', 'Nongstoin', 'Baghmara'],
  'Mizoram': ['Aizawl', 'Lunglei', 'Champhai', 'Serchhip', 'Kolasib'],
  'Nagaland': ['Kohima', 'Dimapur', 'Mokokchung', 'Tuensang', 'Wokha', 'Mon'],
  'Odisha': [
    'Bhubaneswar', 'Cuttack', 'Rourkela', 'Brahmapur', 'Sambalpur', 'Puri', 'Balasore',
    'Bhadrak', 'Baripada', 'Jharsuguda', 'Bargarh', 'Angul', 'Paradip',
  ],
  'Puducherry': ['Puducherry', 'Karaikal', 'Mahe', 'Yanam'],
  'Punjab': [
    'Ludhiana', 'Amritsar', 'Jalandhar', 'Patiala', 'Bathinda', 'Mohali', 'Pathankot',
    'Hoshiarpur', 'Batala', 'Moga', 'Abohar', 'Malerkotla', 'Muktsar', 'Phagwara',
    'Firozpur', 'Gurdaspur', 'Kapurthala', 'Zirakpur',
  ],
  'Rajasthan': [
    'Jaipur', 'Jodhpur', 'Kota', 'Bikaner', 'Ajmer', 'Udaipur', 'Bhilwara', 'Alwar',
    'Sikar', 'Bharatpur', 'Pali', 'Sri Ganganagar', 'Barmer', 'Churu', 'Jhunjhunu',
    'Tonk', 'Beawar', 'Hanumangarh', 'Jaisalmer', 'Bundi',
  ],
  'Sikkim': ['Gangtok', 'Namchi', 'Gyalshing', 'Mangan'],
  'Tamil Nadu': [
    'Chennai', 'Coimbatore', 'Madurai', 'Tiruchirappalli', 'Salem', 'Tirunelveli',
    'Vellore', 'Erode', 'Thoothukudi', 'Tiruppur', 'Dindigul', 'Thanjavur',
    'Ranipet', 'Sivakasi', 'Karur', 'Udhagamandalam', 'Hosur', 'Nagercoil', 'Kancheepuram',
    'Kumarapalayam', 'Karaikkudi', 'Neyveli', 'Cuddalore',
  ],
  'Telangana': [
    'Hyderabad', 'Warangal', 'Nizamabad', 'Karimnagar', 'Khammam', 'Ramagundam',
    'Mahbubnagar', 'Nalgonda', 'Adilabad', 'Suryapet', 'Miryalaguda', 'Siddipet',
    'Zahirabad', 'Mancherial', 'Narayanpet', 'Sangareddy',
  ],
  'Tripura': ['Agartala', 'Udaipur', 'Dharmanagar', 'Kailasahar', 'Belonia'],
  'Uttar Pradesh': [
    'Lucknow', 'Kanpur', 'Agra', 'Varanasi', 'Prayagraj', 'Meerut', 'Ghaziabad',
    'Noida', 'Mathura', 'Aligarh', 'Gorakhpur', 'Bareilly', 'Moradabad', 'Saharanpur',
    'Firozabad', 'Jhansi', 'Muzaffarnagar', 'Hapur', 'Rampur', 'Shahjahanpur',
    'Farrukhabad', 'Mau', 'Haridwar (border)', 'Bulandshahr', 'Unnao', 'Hardoi',
  ],
  'Uttarakhand': [
    'Dehradun', 'Haridwar', 'Roorkee', 'Haldwani', 'Rudrapur', 'Kashipur',
    'Rishikesh', 'Nainital', 'Almora', 'Mussoorie', 'Pithoragarh', 'Kotdwar',
  ],
  'West Bengal': [
    'Kolkata', 'Howrah', 'Durgapur', 'Asansol', 'Siliguri', 'Bardhaman', 'Malda',
    'Baharampur', 'Habra', 'Kharagpur', 'Shantipur', 'Dankuni', 'Dhulian',
    'Ranaghat', 'Haldia', 'Raiganj', 'Krishnanagar', 'Nabadwip', 'Medinipur',
    'Jalpaiguri', 'Balurghat', 'Basirhat', 'Bankura', 'Darjeeling', 'Purulia',
  ],
};
